name: Release

on:
    push:
        tags:
            - "*"

env:
    EDP_SCHEMA_JSON: edp_schema_${{ github.ref_name }}.json
    WHEEL_NAME: extended_dataset_profile.whl
    EDP_SCHEMA_README: extended_dataset_profile_${{ github.ref_name }}.md
    PYTHON_VERSION: 3.12

jobs:
    build_wheel:
        runs-on: ubuntu-24.04
        name: Build Release Wheel
        env:
            DISTRIBUTION_DIR: "${{ github.workspace }}/dist"
            VERSION: "${{ github.ref_name }}"
        steps:
            - uses: actions/checkout@v4
            - uses: astral-sh/setup-uv@v5
              with:
                  python-version: ${{ env.PYTHON_VERSION }}
            - name: Install optional dependencies
              run: uv sync --all-extras

            - name: Build Wheel
              run: uv tool run hatch build
            - uses: actions/upload-artifact@v4
              with:
                  name: ${{ env.WHEEL_NAME }}
                  path: "${{ env.DISTRIBUTION_DIR }}/extended_dataset_profile*.whl"
                  if-no-files-found: error

    generate_schemas:
        runs-on: ubuntu-24.04
        name: Generate Schemas
        needs:
            - build_wheel
        steps:
            - uses: astral-sh/setup-uv@v5
              with:
                  python-version: ${{ env.PYTHON_VERSION }}
            - uses: actions/download-artifact@v4
              id: download_wheel
              with:
                  name: ${{ env.WHEEL_NAME }}
                  path: ${{ github.workspace }}

            - name: Install
              run: uv pip install ${{ steps.download_wheel.outputs.download-path }}/extended_dataset_profile-*.whl

            - name: Generate EDP Schema
              run: export_edp_schema --output ${{ env.EDP_SCHEMA_JSON }}
            - uses: actions/upload-artifact@v4
              with:
                  name: ${{ env.EDP_SCHEMA_JSON }}
                  path: ${{ env.EDP_SCHEMA_JSON }}

    edp-readme:
        runs-on: ubuntu-24.04
        name: Create EDP Readme
        steps:
        -   uses: actions/checkout@v4
        -   uses: astral-sh/setup-uv@v5
            with:
                python-version: ${{ env.PYTHON_VERSION }}
        -   name: Install
            run: uv sync --all-extras
        -   name: Run pydantic markdown generator
            run: pydantic_markdown --model extended_dataset_profile.ExtendedDatasetProfile --output ${{ env.EDP_SCHEMA_README }}
        -   name: Upload readme
            uses: actions/upload-artifact@v4
            with:
                name: ${{ env.EDP_SCHEMA_README }}
                path: ${{ env.EDP_SCHEMA_README }}

    create_release:
        runs-on: ubuntu-24.04
        name: Create Release
        needs:
            - build_wheel
            - generate_schemas
            - edp-readme
        env:
            ARTIFACTS_DIR: ${{ github.workspace }}/release_artifacts
        steps:
            - name: Create Directory for artifacts
              run: mkdir -p ${{ env.ARTIFACTS_DIR }}
            - uses: actions/download-artifact@v4
              with:
                  name: ${{ env.EDP_SCHEMA_JSON }}
                  path: ${{ env.ARTIFACTS_DIR }}

            - uses: actions/download-artifact@v4
              with:
                  name: ${{ env.WHEEL_NAME }}
                  path: ${{ env.ARTIFACTS_DIR }}
            - uses: actions/download-artifact@v4
              with:
                  name: ${{ env.EDP_SCHEMA_README }}
                  path: ${{ env.ARTIFACTS_DIR }}
    
            - name: Release
              uses: softprops/action-gh-release@v2
              with:
                  body: "Extended Dataset Profile Schema: ${{ github.ref_name }}\n\n"
                  body_path:  "${{ env.ARTIFACTS_DIR }}/${{ env.EDP_SCHEMA_README }}"
                  files: ${{ env.ARTIFACTS_DIR }}/*
                  fail_on_unmatched_files: true
                  draft: true
                  generate_release_notes: true
